server:
    port: 9001

spring:
    application:
        name: devices 
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibenate:
                dialect: org.hibernate.dialect.MariaDBDialect
    datasource:
        url: jdbc:mysql://localhost:3306/remotetemperature
        username: root
        password: yq7z88YSELzue3cT
        driver-class-name: org.mariadb.jdbc.Driver
