server:
    port: 8082

eureka:
    instance:
        hostname: localhost
    client: 
        service-url:
            defaultZone: http://localhost:8081/eureka/
        fetch-registry: true
        register-with-eureka: true

spring:
    application:
        name: frontend
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp