spring:
    application:
        name: gateway
    cloud:
        gateway:
            routes:
                -   id: data
                    uri: lb://data
                    predicates:
                    -   Path=/data/**
                -   id: mqtt
                    uri: lb://mqtt
                    predicates:
                        -   Path=/mqtt/**
                -   id: devices
                    uri: lb://devices
                    predicates:
                        -   Path=/devices/**
                -   id: frontend
                    uri: lb://frontend
                    predicates:
                        -   Path=/**


server:
    port: 8080
    servlet:
        context-path: /gateway

eureka:
    instance:
        hostname: localhost
    client: 
        service-url:
            defaultZone: http://localhost:8081/eureka/
        fetch-registry: true
        register-with-eureka: true

    
