spring:
    application:
        name: gateway
    cloud:
        gateway:
            routes:
                -   id: frontend
                    uri: lb:/frontend
                    predicates:
                        -   Path=/**

                -   id: devices
                    uri: lb://devices
                    predicates:
                        -   Path=/devices/**

server:
    port: 8080
    servlet:
        context-path: /gateway

eureka:
    instance:
        hostname: localhost
    client: 
        service-url:
            defaultZone: http://localhost:8081/eureka/
        fetch-registry: true
        register-with-eureka: true

    
